### ISSUE TITLE
[Bug]: FFXIV 7.2 broke textools

### ISSUE THREAD

**Issue by sevus09** [TexTools/xivModdingFramework#86]
### Expected behavior?

Post-patch maintenance will not complete after patch 7.2 of FFXIV. Will not work whatsoever.

### Actual behavior?

post-patch maintenance will not complete.

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [x] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Scylune** [comment]
Hello, I second this. I started over before the patch. More details : 

![Image](https://github.com/user-attachments/assets/85d1de79-d17c-4960-a41a-891b3cc2d76d)

**Comment by Squall-Leonhart** [comment]
Fixed by https://github.com/TexTools/xivModdingFramework/commit/8e3603aa22d09b207c06b9190379c9695b12ea5d

**Comment by sevus09** [comment]
> Fixed by [8e3603a](https://github.com/TexTools/xivModdingFramework/commit/8e3603aa22d09b207c06b9190379c9695b12ea5d)

@Squall-Leonhart I see you set this to closed? I'm not entirely sure what "Fixed by 8e3603a" means? Any clarification? The textools exe hasn't been updated nor has the problem been fixed? Did I just submit the issue somewhere incorrect or something?

**Comment by ZoraXIV** [comment]
@Squall-Leonhart +1 to issue still present in live as of 3/29/2025 at 4:07PM Pacific. Even uninstalled and reinstalled TexTools.

![Image](https://github.com/user-attachments/assets/cb43d798-b1c3-4c1d-8c55-d25ccd20d8c9)
